# Generated by Django 3.2.20 on 2023-07-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20230724_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team2',
            old_name='desc2',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='img2',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='name2',
            new_name='name',
        ),
    ]
