# Generated by Django 3.2.20 on 2023-07-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20230724_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team2',
            old_name='desc',
            new_name='Member_desc',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='img',
            new_name='Member_img',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='name',
            new_name='Member_name',
        ),
    ]
