# Generated by Django 3.2.20 on 2023-07-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20230724_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team2',
            old_name='Member_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='Member_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team2',
            old_name='Member_name',
            new_name='name',
        ),
    ]
